constants:

  cloudfront:
    domain: <%= ENV['CW_CLOUDFRONT_DOMAIN'] %>

  company_api:
    root_url: <%= ENV['CW_CA_ROOT_URL'] %>
    basic_auth_user: <%= ENV['CW_CA_BASIC_AUTH_USER'] %>'
    basic_auth_pass: <%= ENV['CW_CA_BASIC_AUTH_PASS'] %>'
    open_timeout: 5
    read_timeout: 5